spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testTask
    username: postgres
    password: 142536
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true

